const ADD_NUMBER = "ADD_NUMBER"
const SUB_NUMBER = "SUB_NUMER"
const SET_NAME = "SET_NAME"
const SET_ARTICLES = "SET_ARTICLES"
const SET_CATEGORIES = "SET_CATEGORIES"
const SET_TAGS = "SET_TAGS"

export {
  ADD_NUMBER,
  SUB_NUMBER,
  SET_NAME,
  SET_ARTICLES,
  SET_CATEGORIES,
  SET_TAGS
}