/** @format */

export const EnumColor = {
  primary: '#1976d2',
  secondary: '#ffc6bf',
  accent: '#816ad6',
  info: '#00cec9',
  success: '#00b894',
  warning: '#fcd783',
  danger: '#f375b5',
}
export const emojis = [
  {title: '大笑', url: '/static/img/smilies/arrow.png'},
  {title: '可爱', url: '/static/img/smilies/biggrin.png'},
  {title: '冷笑', url: '/static/img/smilies/confused.png'},
  {title: '酷', url: '/static/img/smilies/cool.png'},
  {title: '牛皮', url: '/static/img/smilies/cowboy.png'},
  {title: '哭', url: '/static/img/smilies/cry.png'},
  {title: '憨笑', url: '/static/img/smilies/drooling.png'},
  {title: '舔', url: '/static/img/smilies/eek.png'},
  {title: '滑稽', url: '/static/img/smilies/evil.png'},
  {title: '惊叫', url: '/static/img/smilies/exclaim.png'},
  {title: '卖萌', url: '/static/img/smilies/idea.png'},
  {title: '难过', url: '/static/img/smilies/mad.png'},
  {title: '汗', url: '/static/img/smilies/mrgreen.png'},
  {title: '疑问', url: '/static/img/smilies/neutral.png'},
  {title: '委屈', url: '/static/img/smilies/persevering.png'},
  {title: '震惊', url: '/static/img/smilies/question.png'},
  {title: '机智', url: '/static/img/smilies/razz.png'},
  {title: '不屑', url: '/static/img/smilies/redface.png'},
  {title: '色', url: '/static/img/smilies/rolleyes.png'},
  {title: '吐', url: '/static/img/smilies/shit.png'},
  {title: '微笑', url: '/static/img/smilies/smile.png'},
  {title: '惊讶', url: '/static/img/smilies/surprised.png'},
  {title: '内涵', url: '/static/img/smilies/symbols.png'},
  {title: '生气', url: '/static/img/smilies/twisted.png'},
  {title: '呵呵', url: '/static/img/smilies/wink.png'},
]
export const icons = [
  '/static/img/food/南瓜.png',
  '/static/img/food/吐司.png',
  '/static/img/food/夏威夷果.png',
  '/static/img/food/山楂片.png',
  '/static/img/food/开心果.png',
  '/static/img/food/抹茶麻薯.png',
  '/static/img/food/杏仁.png',
  '/static/img/food/板栗.png',
  '/static/img/food/柠檬干.png',
  '/static/img/food/炭烤肠.png',
  '/static/img/food/猪肉铺.png',
  '/static/img/food/瓜子.png',
  '/static/img/food/芒果干.png',
  '/static/img/food/花生.png',
  '/static/img/food/草莓干.png',
  '/static/img/food/蒸蛋糕.png',
  '/static/img/food/蚕豆.png',
  '/static/img/food/蛋黄酥.png',
  '/static/img/food/辣条.png',
  '/static/img/food/鱿鱼仔.png',
]
